[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "lerobot-experiments"
version = "0.1.0"
description = "Custom experiments and tooling built on top of the upstream lerobot package."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "Apache-2.0" }
authors = [
    { name = "Zarin Gleb" },
]
dependencies = [
    "ipykernel>=6.30.1",
    "ipywidgets>=8.1.7",
    "lerobot>=0.3.3",
    "matplotlib>=3.10.6",
]

[project.optional-dependencies]
dev = ["ruff", "pytest"]

[project.scripts]
lerobot-experiments-train = "lerobot_experiments.scripts.train:main"
lerobot-experiments-record = "lerobot_experiments.scripts.record:main"
lerobot-experiments-remove-episodes = "lerobot_experiments.utils.remove_episodes_from_dataset:main"

[tool.setuptools.packages.find]
where = ["src"]
